# Generated by Django 2.2.7 on 2019-12-08 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '__first__'),
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(verbose_name='Дата заказа')),
                ('order_state', models.CharField(max_length=100, verbose_name='Статус заказа')),
                ('order_price', models.FloatField(verbose_name='Стоимость заказа')),
                ('order_payed', models.FloatField(verbose_name='Оплачено')),
                ('order_comment', models.TextField(verbose_name='Комментарий')),
                ('order_image', models.FileField(upload_to='', verbose_name='Дизайн')),
                ('order_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Client')),
                ('order_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Service')),
                ('order_worker', models.ManyToManyField(to='users.Worker')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
