# Generated by Django 2.2.7 on 2019-12-08 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('services', '0002_delete_review'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_pubdate', models.DateTimeField(verbose_name='Дата публикации')),
                ('review_telephonenumber', models.CharField(max_length=11, verbose_name='Номер телефона')),
                ('review_email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('review_text', models.TextField(verbose_name='Текст отзыва')),
                ('review_screenshot', models.FileField(upload_to='', verbose_name='Скриншот')),
                ('review_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Client')),
                ('review_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Service')),
                ('review_worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Worker')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='ReviewAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewanswer_text', models.TextField(verbose_name='Текст')),
                ('reviewanswer_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Worker')),
                ('reviewanswer_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Review')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
            },
        ),
    ]
