# Generated by Django 2.2.8 on 2019-12-21 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20191221_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review_name',
            field=models.TextField(blank=True, null=True, verbose_name='Имя(если не зарегстрирован)'),
        ),
    ]
