# Generated by Django 2.2.8 on 2019-12-21 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_review_review_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя(если не зарегстрирован)'),
        ),
    ]
