# Generated by Django 2.2.8 on 2019-12-21 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20191221_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя(если не зарегстрирован)'),
        ),
    ]
