# Generated by Django 2.2.8 on 2019-12-21 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_order_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_email',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='E-mail(если не зарегстрирован)'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_telephonenumber',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Телефон(если не зарегстрирован)'),
        ),
    ]
