# Generated by Django 2.2.8 on 2019-12-21 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_orderchatmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderchatmessage',
            name='message_client',
        ),
        migrations.RemoveField(
            model_name='orderchatmessage',
            name='message_worker',
        ),
        migrations.AddField(
            model_name='orderchatmessage',
            name='message_author',
            field=models.CharField(default='раб', max_length=100, verbose_name='Автор'),
            preserve_default=False,
        ),
    ]
