# Generated by Django 2.2.8 on 2019-12-25 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20191221_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderchatmessage',
            name='message_image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Картинка'),
        ),
    ]
