# Generated by Django 2.2.7 on 2019-12-08 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrintType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('printtype_name', models.CharField(max_length=200, verbose_name='Название типа печати')),
            ],
            options={
                'verbose_name': 'Тип печати',
                'verbose_name_plural': 'Типы печати',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=200, verbose_name='Название услуги')),
                ('service_price', models.FloatField(verbose_name='Цена услуги')),
                ('service_description', models.TextField(verbose_name='Описание услуги')),
                ('service_printtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.PrintType')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_name', models.CharField(max_length=100, verbose_name='Название акции')),
                ('sale_datestart', models.DateTimeField(verbose_name='Дата начала')),
                ('sale_dateend', models.DateTimeField(verbose_name='Дата конца')),
                ('sale_description', models.TextField(verbose_name='Описание')),
                ('sale_image', models.FileField(upload_to='', verbose_name='Изображение')),
                ('sale_service', models.ManyToManyField(to='services.Service')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_pubdate', models.DateTimeField(verbose_name='Дата публикации')),
                ('review_telephonenumber', models.CharField(max_length=11, verbose_name='Номер телефона')),
                ('review_email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('review_text', models.TextField(verbose_name='Текст отзыва')),
                ('review_screenshot', models.FileField(upload_to='', verbose_name='Скриншот')),
                ('review_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Service')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
