# Generated by Django 2.2.7 on 2019-12-10 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20191210_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_image',
            field=models.ImageField(default='index.jpg', upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_image',
            field=models.ImageField(upload_to=''),
        ),
    ]
