# Generated by Django 2.2.7 on 2019-12-08 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clienttype_name', models.CharField(max_length=200, verbose_name='Тип клиента')),
            ],
            options={
                'verbose_name': 'Тип клиента',
                'verbose_name_plural': 'Типы клиентов',
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_name', models.CharField(max_length=100, verbose_name='ФИО Работника')),
                ('worker_telephonenumber', models.CharField(max_length=11, verbose_name='Номер телефона')),
                ('worker_password', models.CharField(max_length=200, verbose_name='Пароль Работника')),
                ('worker_email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('worker_birthdaydate', models.DateField(verbose_name='Дата рождения')),
                ('worker_printtype', models.ManyToManyField(to='services.PrintType')),
                ('worker_service', models.ManyToManyField(to='services.Service')),
            ],
            options={
                'verbose_name': 'Работник',
                'verbose_name_plural': 'Работники',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100, verbose_name='ФИО Клиента')),
                ('client_telephonenumber', models.CharField(max_length=11, verbose_name='Номер телефона')),
                ('client_password', models.CharField(max_length=200, verbose_name='Пароль Клиента')),
                ('client_email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('client_birthdaydate', models.DateField(verbose_name='Дата рождения')),
                ('client_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.ClientType')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
    ]
