# Generated by Django 2.2.7 on 2019-12-10 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='worker_image',
            field=models.ImageField(default='index.jpg', upload_to=''),
            preserve_default=False,
        ),
    ]
